language: ruby

sudo: false

rvm:
  - 2.2.4
  - 2.3.0
  - ruby-head

gemfile:
  - gemfiles/active_record_41.gemfile
  - gemfiles/active_record_42.gemfile
  - gemfiles/active_record_edge.gemfile

cache: bundler
